// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY-ahSm9-dRx2-XKyAnNw__bJs0mvnw4I',
    appId: '1:796000540763:web:b5b2f8b7d3c072ffe0077e',
    messagingSenderId: '796000540763',
    projectId: 'fire-17e9d',
    authDomain: 'fire-17e9d.firebaseapp.com',
    storageBucket: 'fire-17e9d.appspot.com',
    measurementId: 'G-6DY59Z1SKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDms9mBbeqMSuwALOq6XXQ0eOQAlNaxTXg',
    appId: '1:796000540763:android:8e6b74112420ab14e0077e',
    messagingSenderId: '796000540763',
    projectId: 'fire-17e9d',
    storageBucket: 'fire-17e9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcuwo1V05u9K59b6uBV5AGulgTxRabNW0',
    appId: '1:796000540763:ios:be250e25b84b9cf0e0077e',
    messagingSenderId: '796000540763',
    projectId: 'fire-17e9d',
    storageBucket: 'fire-17e9d.appspot.com',
    iosBundleId: 'com.example.firebaru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcuwo1V05u9K59b6uBV5AGulgTxRabNW0',
    appId: '1:796000540763:ios:be250e25b84b9cf0e0077e',
    messagingSenderId: '796000540763',
    projectId: 'fire-17e9d',
    storageBucket: 'fire-17e9d.appspot.com',
    iosBundleId: 'com.example.firebaru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY-ahSm9-dRx2-XKyAnNw__bJs0mvnw4I',
    appId: '1:796000540763:web:d2b9dc2ac66a5d89e0077e',
    messagingSenderId: '796000540763',
    projectId: 'fire-17e9d',
    authDomain: 'fire-17e9d.firebaseapp.com',
    storageBucket: 'fire-17e9d.appspot.com',
    measurementId: 'G-MFCCVMF49G',
  );
}
